apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-app-service-monitor
  namespace: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
  - port: http
    path: /metrics
    targetPort: 5000
  namespaceSelector:
    matchNames:
    - default
    