apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.cmName }}
data:
  # MONGODB_URI: "mongodb://mongo-0.mongodb.default.svc.cluster.local:27017,mongo-1.mongodb.default.svc.cluster.local:27017,mongo-2.mongodb.default.svc.cluster.local:27017/blog"
  # MONGO_URI: "mongodb://root:password@mongo-0.mongodb.default.svc.cluster.local:27017/blog"
  MONGO_URI: "mongodb://root:password@mongo-0.mongodb:27017/blog?authSource=admin"

  PERSISTENCE: "true"
  LOG_LEVEL: "info"
